#!/bin/bash

set -euo pipefail

kubectl get pod vader -o jsonpath='{.spec.containers[0].image}' | grep -q -w 'nginx'
kubectl get pod vader -o jsonpath='{.spec.containers[0].volumeMounts[?(@.name=="vader-vol")].mountPath}' | grep -q -w '/var/www/html'
