#!/bin/bash

set -euo pipefail

kubectl get po dooku -o jsonpath='{.spec.containers[0].volumeMounts[?(@.name=="dooku-logs")].mountPath}' | grep -q -w '/var/log/dooku'
kubectl get po dooku -o jsonpath='{.spec.containers[1].volumeMounts[?(@.name=="dooku-logs")].mountPath}' | grep -q -w '/var/log/dooku'
# can't do hostpath
#kubectl get po dooku -o jsonpath='{.spec.volumes[?(@.name=="dooku-logs")].hostPath.path}' | grep -q -w '/data/dooku'
# so..
kubectl get po dooku -o jsonpath='{.spec.volumes[?(@.name=="dooku-logs")].emptyDir}' | grep -q -w '{}'
kubectl get po dooku -o jsonpath='{.status.phase}' | grep -q -w 'Running'
